accounts/urls.py
from .views import *
from django.urls import path,include
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [

    path('' , login_attempt , name="login"),
    path('register' , register , name="register"),
    path('otp' , otp , name="otp"),
    path('login-otp', login_otp , name="login_otp"),
    path('logout', auth_views.LogoutView.as_view(), name="logout"),
]

blindRead/urls.py
from re import template
from django.contrib import admin
from django.urls import path, include
from interface import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePageView.as_view(), name='home'),
    path('', include('pwa.urls')),
    path('upload',views.upload, name='upload'),
    path('accounts/', include('accounts.urls')),
]



urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime
# Create your models here.

class User(AbstractUser):

    def __str__(self):
        return self.first_name

class Profile(models.Model):
    user = models.OneToOneField(User ,on_delete=models.CASCADE)
    mobile = models.CharField(max_length=20)
    otp = models.CharField(max_length=6)
    last_use_date = models.DateField(default=datetime.now)
    counter = models.PositiveIntegerField(default=5)
    

interface/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.contrib import auth
from django.shortcuts import render , redirect

import ssl
ssl._create_default_https_context = ssl._create_unverified_context

from .models import Profile, User
import random
from django.core.exceptions import ValidationError
import http.client
import requests

from django.conf import settings
from django.contrib.auth import authenticate, login

# Create your views here.


def send_otp(mobile , otp):
    print("FUNCTION CALLED")
    url = "https://www.fast2sms.com/dev/bulk"
    payload = "sender_id=FSTSMS&message=Here%20is%20your%20OTP%20for%20BlindRead%20"+ otp + "&language=english&route=p&numbers="+mobile
    headers = {
        'authorization': "SHiz8hcE1IqksePRrNUfvj35AVodQyZmaCYTWFtxpMJ42X06KBO1LokJ7PWD5bxRtIC3zrHqnavNflEY",
        'Content-Type': "application/x-www-form-urlencoded",
        'Cache-Control': "no-cache",
    }
    response = requests.request("POST", url, data=payload, headers=headers)
    print(response)
    return None



def login_attempt(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        print("email id is: ", email)
        print("password is: ", password)
        user = User.objects.filter(email=email).first()
        if user is None:
            print("User is none")
            context = {'message' : 'User not found' , 'class' : 'danger' }
            return render(request,'accounts/login.html' , context)
        else:
            if password == user.password:
                login(request, user)
                print("User logged in")
                return redirect('home')
            else:
                return render(request,'accounts/login.html')

    return render(request,'accounts/login.html')


def login_otp(request):
    mobile = request.session['mobile']
    context = {'mobile':mobile}
    if request.method == 'POST':
        otp = request.POST.get('otp')
        profile = Profile.objects.filter(mobile=mobile).first()
        
        if otp == profile.otp:
            user = User.objects.get(id = profile.user.id)
            login(request , user)
            return redirect('home')
        else:
            context = {'message' : 'Wrong OTP' , 'class' : 'danger','mobile':mobile }
            return render(request,'accounts/login_otp.html' , context)
    
    return render(request,'accounts/login_otp.html' , context)
    
    

def register(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        name = request.POST.get('name')
        mobile = request.POST.get('mobile')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        else:
            password = password2
        

        check_user = User.objects.filter(email = email).first()
        check_profile = Profile.objects.filter(mobile = mobile).first()
        
        if check_user or check_profile:
            context = {'message' : 'User already exists' , 'class' : 'danger' }
            return render(request,'accounts/register.html' , context)
        
        # print(email, name, password)
        user = User(email = email , first_name = name, password = password)
        # user = User(email = email , first_name = name)
        user.save()
        otp = str(random.randint(1000 , 9999))
        profile = Profile(user = user , mobile = mobile , otp = otp) 
        profile.save()
        send_otp(mobile, otp)
        print(otp)
        request.session['mobile'] = mobile
        return redirect('accounts:otp')
    return render(request,'accounts/register.html')

def otp(request):
    mobile = request.session['mobile']
    context = {'mobile':mobile}
    if request.method == 'POST':
        otp = request.POST.get('otp')
        profile = Profile.objects.filter(mobile=mobile).first()
        if otp == profile.otp:
            return redirect('home')
        else:
            print('Wrong')
            
            context = {'message' : 'Wrong OTP' , 'class' : 'danger','mobile':mobile }
            return render(request,'accounts/otp.html' , context)
            
        
    return render(request,'accounts/otp.html' , context)

interface/views.py
from django.core.exceptions import ImproperlyConfigured
from django.shortcuts import render
from django.views import generic
from django.core.files.storage import FileSystemStorage
import datetime
from django.utils import timezone
import pathlib
from convert_pdf_to_audio import convert_pdf_to_audio
import os
from gtts import gTTS
from gtts import lang
import datetime
from accounts import models as acct_mdls
# Create your views here.


class HomePageView(generic.TemplateView):
    template_name = 'index.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            profile = acct_mdls.Profile.objects.get(user = request.user)
            if not profile.last_use_date == datetime.date.today():
                profile.counter = 5
                profile.save()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = None
        if self.request.user.is_authenticated:
            profile = acct_mdls.Profile.objects.get(user = self.request.user)
        if profile:    
            context["counter"] = profile.counter
        return context
    


def upload(request):
    if request.method == 'POST':
        if not 'file_name' in request.FILES.keys():
            return render(request, 'index.html')

        profile = acct_mdls.Profile.objects.get(user = request.user)
        phone_number = profile.mobile
        uploaded_file = request.FILES['file_name']
        print(uploaded_file)
        # check if uploaded file in txt using some validation

        print(uploaded_file.size)
        # upload the file onto the created database under the logined user
        fs = FileSystemStorage()
        name = fs.save(phone_number + '/'+uploaded_file.name, uploaded_file)
        print(name)
        first_name = ''
        for c in uploaded_file.name:
            if c != '.':
                first_name += c
            else:
                break

        pathlib.Path('./media/'+phone_number).mkdir(exist_ok=True)
        processing_pages = convert_pdf_to_audio(uploaded_file.name, 'media/'+phone_number, profile.counter)
        
        profile.counter -= processing_pages
        profile.last_use_date = datetime.date.today()
        profile.save()
        
        context = {
            "file_name": uploaded_file.name,
            "output_file": 'audio.mp3',
            "url1": fs.url(name),
            "url2": fs.url(phone_number+'/audio.mp3')
        }
        if request.user.is_authenticated:
            profile = acct_mdls.Profile.objects.get(user = request.user)
            context['counter'] = profile.counter
 

    return render(request, 'upload.html', context)

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% block content %}

<div class="container mt-5 pt-4">
    
    <div class="col-6 mx-auto">
        <h3 class="text-center">Login</h3>
        <form method="post">
            {% csrf_token %}
            <div class="row">
                <div class="form-group col-12">
                    <input type="text" placeholder="Email" class="form-control" name="email" id="">
                </div>
            </div>
            <div class="row">
                <div class="form-group col-12">
                    <input type="password" placeholder="Password" class="form-control" name="password" id="">
                </div>
            </div>

            <p>Don't have account? <a href="{% url 'accounts:register' %}">Register</a></p>
            <button class="btn btn-primary">Submit</button>
        </form>
    </div>

</div>


{% endblock %}

accounts/templates/accounts/login_otp.html
{% extends "base.html" %}
{% block content %}



<div class="container mt-5 pt-4">
    
    <div class="col-6 mx-auto">
        <h3 class="text-center">Enter OTP sent to your number {{mobile}}</h3>
        {% if message %}
        <div class="alert alert-{{class}}">
            {{message}}
        </div>
        {% endif %}

        <form class="mt-2" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="form-group col-12 mt-3">
                    <input type="text" placeholder="Enter otp" class="form-control" name="otp" id="">
                </div>
            </div>

            <p>Don't have account <a href="{% url 'accounts:register' %}">Register</a></p>
            <button class="btn btn-primary">Submit</button>
        </form>
    </div>

</div>


{% endblock %}

accounts/templates/accounts/otp.html
{% extends "base.html" %}
{% block content %}



<div class="container mt-5 pt-4">
    
    <div class="col-6 mx-auto">
        <h3 class="text-center">Enter OTP sent to your number {{mobile}}</h3>
        {% if message %}
        <div class="alert alert-{{class}}">
            {{message}}
        </div>
        {% endif %}

        <form class="mt-2" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="form-group col-12 mt-3">
                    <input type="text" placeholder="Enter otp" class="form-control" name="otp" id="">
                </div>
            </div>

            <p>Don't have account <a href="{% url 'accounts:register' %}">Register</a></p>
            <button class="btn btn-primary">Submit</button>
        </form>
    </div>

</div>


{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}
{% block content %}



<div class="container mt-5 pt-4">
    
    <div class="col-6 mx-auto">
        <h3 class="text-center">Register</h3>
        <form method="post">
            {% csrf_token %}

            {% if message %}
            <div class="alert alert-{{class}}">
                {{message}}
            </div>
            {% endif %}

            <div class="row">
                <div class="form-group col-12">
                    <input type="text" placeholder="Email" class="form-control" name="email" id="">
                </div>
            </div>
            <div class="row">
                <div class="form-group col-12">
                    <input type="text" placeholder="Name" class="form-control" name="name" id="">
                </div>
            </div>
            <div class="row">
                <div class="form-group col-12">
                    <input type="text" placeholder="Mobile" class="form-control" name="mobile" id="">
                </div>
            </div>
            <div class="row">
                <div class="form-group col-12">
                    <input type="password" placeholder="Password" class="form-control" name="password1" id="">
                </div>
            </div>
            <div class="row">
                <div class="form-group col-12">
                    <input type="password" placeholder="Confirm Password" class="form-control" name="password2" id="">
                </div>
            </div>

            <p>Already have account ? <a href="{% url 'accounts:login' %}">Login</a></p>
            <button class="btn btn-primary">Submit</button>
        </form>
    </div>

</div>


{% endblock %}

templates/base.html
{% load static %}
{% load pwa %}

<!DOCTYPE html>
<html lang="en" style="height: 100%">
{% progressive_web_app_meta %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="manifest" href="{% static 'manifest.json' %}">
    <link rel="apple-touch-icon" href="{% static 'images/icon-192.png' %}">
    <meta name="theme-color" content="#009578">
    <title>BlindRead</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'BlindRead/css/master.css' %}">
</head>
<body style="background-image: {% static 'images/bg.png' %}; background-repeat : no-repeat; background-size: cover; height : 100%; background-position:center;">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
        <a class="navbar-brand" href="{% url 'home' %}">BlindRead</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="#" class="nav-link disabled">Number of attempts left today: {{ counter }}</a> 
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'accounts:logout' %}" class="nav-link">Logout</a>
                    </li>
                {% else %}
                <li class="nav-item">
                    <a href="{% url 'accounts:login' %}" class="nav-link">Login</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'accounts:register' %}" class="nav-link">Sign Up</a>
                </li>
                {% endif %}
                
            </ul>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
    <div class='container'>
            <div class='jumbotron bg-dark text-white'  style="opacity: 90%;">
            {% if user.is_authenticated %}
                <h1>Hey, {{user.username}}</h1>
            {% endif %}
            <h1>
            <h2>Math Reader for the Blind</h2>
            <h4>Convert PDF files containing  mathematical equations into Audio</h4>
            </div> 
    </div>  
    <div class="container" style="align-items: center; align-content: center; justify-content: center; display: flex;">
        {% if user.is_authenticated %}
        {% if counter > 0 %}
        <form action="upload" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
                <div class="jumbotron bg-dark text-white">
                    <input type="file" value="Upload PDF" id="upload" name="file_name" hidden/>
                    <label for="upload"><h3><i class="fa fa-upload" style="font-size: 48px;"></i>Upload File</h3></label>
                    <br>
                    <button type="submit" for="upload" class="btn btn-danger">Convert to Audio</button>
                </div>
        </form>
        {% else %}
        <div class="jumbotron bg-danger text-white" style="opacity:90%;">
                <div class="container" style="align-items: center;">
                    <h2> 
                        You have run out of number of attempts. Please subscribe or try again tomorrow. 
                    </h2>
                </div>
            </div>
        {% endif %}
        {% else %}
            <div class="jumbotron bg-danger text-white" style="opacity:90%;">
                <div class="container" style="align-items: center;">
                    <h2> 
                        <a href="{% url 'accounts:login' %}">Login</a> to be able to use this service. Click here to <a href="{% url 'accounts:register' %}">Sign up </a> 
                    </h2>
                </div>
            </div>
        {% endif %}    
    </div>
{% endblock content %}
        

templates/upload.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="jumbotron bg-dark text-white" style="opacity: 90%;">
        <div class="container">
            <h1>Uploaded file: <a href="{{url1}}" target="_blank">{{ file_name }}</a></h1>
            <h1>Audio Output:
                <audio controls>
                    <source src="{{ url2 }}" type="audio/mpeg">
                    Your browser does not support the audio element.
                </audio>
            </h1>
            <p>Click here to download the audio file:<a href="{{url2}}" target="_blank">{{ output_file }}</a></p>
        </div>
    </div>
</div>

{% endblock content %}